# Generated by Django 4.0.2 on 2022-08-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="parent_show",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="podcasts.show",
            ),
            preserve_default=False,
        ),
    ]
