# Generated by Django 4.0.2 on 2022-08-19 18:56

import podcasts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_episode_parent_show"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="file_length",
        ),
        migrations.AlterField(
            model_name="episode",
            name="duration",
            field=models.IntegerField(help_text="Length of episode in seconds"),
        ),
        migrations.AlterField(
            model_name="episode",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Overrides the show art for this episode in specific. Defaults to Show art if null.",
                null=True,
                upload_to="",
                validators=[podcasts.utils.validate_show_art_is_optimally_sized],
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="link",
            field=models.URLField(
                help_text="Link to a specific page for show notes for this episode"
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="published_date",
            field=models.DateTimeField(
                help_text="The publication date of this episode. Used to determine what shows to include in the RSS feed"
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="author",
            field=models.CharField(
                help_text="The name of this shows hosts as you'd like them displayed within a podcast directory",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="block",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="Whether this show is displayed in the Apple Itunes Directory. Set to YES if you don't want this show to be published yet",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="complete",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="Whether this show is complete. Set to YES if this show has concluded and will no longer be publishing new content",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="explicit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="show",
            name="image",
            field=models.ImageField(
                help_text="Should be a 3000x3000 square image",
                upload_to="",
                validators=[podcasts.utils.validate_show_art_is_optimally_sized],
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="link",
            field=models.URLField(help_text="The homepage for your podcast"),
        ),
        migrations.AlterField(
            model_name="show",
            name="owner_email",
            field=models.EmailField(
                help_text="The email of this shows primary point of contact (Not displayed in podcast directories)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="owner_name",
            field=models.CharField(
                help_text="The name of this shows primary point of contact (Not displayed in podcast directories)",
                max_length=120,
            ),
        ),
    ]
