# Generated by Django 4.0.2 on 2022-08-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0003_remove_episode_file_length_alter_episode_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="html_description",
            field=models.TextField(blank=True, editable=False, max_length=4000),
        ),
        migrations.AlterField(
            model_name="show",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
