# Generated by Django 4.0.2 on 2022-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0005_alter_show_explicit"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="slug_title",
            field=models.SlugField(
                blank=True,
                help_text="Slug support if you opt for a multi-show hosting solution",
            ),
        ),
    ]
